version: "3.9"
services:
  backend:
    container_name: backend
#    image: aguzf/cursos:latest
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - spring
  front:
    container_name: front
#    image: nginx:1.23.3
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - 4200:80  
    restart: always
networks:
  spring:
    name: spring
    #external: true      