version: "3.9"
services:
  front:
    container_name: front
#    image: nginx:1.23.3
    build:
      context: C:\Users\Elitebook\Desktop\proyecto\lubricampeon-erp
      dockerfile: ./Dockerfile
    ports:
      - 8000:80      
#  angular-nginx-docker:
#    image: angular-nginx-docker
#    build: .
#    environment:
#      NODE_ENV: production
#    ports:
#      - 80:80
